env:
  es2021: true
  node: true
  screeps/screeps: true
extends: 
  - "google"
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  require-jsdoc: 0
  max-len:
    - error
    - code: 120
  indent: off
  tsdoc/syntax: warn
plugins:
 - screeps
 - eslint-plugin-tsdoc